
sudo: false

language: python

matrix:
  include:
    - os: linux
      python: '3.6'
      script: flake8 clifford
      stage: Lint
    - os: linux
      python: '3.5'
      env: CONDA=false
      stage: Test
    - os: linux
      python: '3.6'
      env: CONDA=false
      stage: Test
    - os: linux
      python: '3.5'
      env: CONDA=true
      stage: Test
    - os: linux
      python: '3.6'
      env: CONDA=true
      stage: Test

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a ; fi

install:
  - |
    if [[ "${CONDA}" == "true" ]]; then
      PYTHON_VERSION="$TRAVIS_PYTHON_VERSION" CONDA_INSTALLER_OS="${TRAVIS_OS_NAME:-linux}" source auto_version/travis_install_conda.sh \
        numpy \
        scipy \
        numba \
        pip \
        h5py \
        pytest \
        pytest-cov;
      conda install -c conda-forge sparse;
      conda install -c numba numba==0.45.1;
    else
      pip install pytest-cov flake8
    fi
  - python setup.py install
  - pip install codecov

script:
  - |
    pytest clifford/test \
      --doctest-modules \
      --junitxml=junit/test-results.xml \
      --durations=25 \
      --cov=clifford \
      --cov-branch

after_success:
  - codecov

deploy:
  provider: pypi
  user: arsenovic
  password:
    secure: ieUd3c2DjrZQE+3FlqmU5FQObNWIDiL9E9G6aLs0ksEKAi5Z1t7fefXic1XHsHOZZYteycef/lZkUYg3ijwfZg2xzELeTdLef29GgUrxYuGL4MJ706UFj450Xlv9l1oH5D32OEKT2EwfxMqdrw39+N8zD5ehVyQbYM6Z3lwtCvg=
  on:
    tags: true
