# there is nothing special about this key, it's just ignored by travis
x-clifford-templates:
  lint_job: &lint_job
    install:
      - pip install flake8
      - pip install .
    script: python -m flake8 clifford

  test_job: &test_job
    install:
      - |
        if [[ "${CONDA}" == "true" ]]; then
          PYTHON_VERSION="$TRAVIS_PYTHON_VERSION" CONDA_INSTALLER_OS="${TRAVIS_OS_NAME:-linux}" source travis_install_conda.sh \
            numpy \
            scipy \
            numba \
            pip \
            h5py;
          conda install -c conda-forge sparse;
          conda install -c numba numba>=0.45.1;
        fi
      # make sure in conda we do not overwrite dependencies with pip
      - |
        if [[ "${CONDA}" == "true" ]]; then
          python setup.py develop --no-deps;
        else
          pip install .;
        fi
      # always install with pip, conda has too old a version
      - pip install pytest pytest-cov pytest-benchmark
      - pip install codecov
    script:
      - |
        pytest clifford/test \
          ${PYTEST_ARGS} \
          --doctest-modules \
          --junitxml=junit/test-results.xml \
          --durations=25 \
          --cov=clifford \
          --cov-branch
    after_success:
      - codecov

  deploy_job: &deploy_job
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: arsenovic
      distributions: "sdist bdist_wheel"
      password:
        secure: ieUd3c2DjrZQE+3FlqmU5FQObNWIDiL9E9G6aLs0ksEKAi5Z1t7fefXic1XHsHOZZYteycef/lZkUYg3ijwfZg2xzELeTdLef29GgUrxYuGL4MJ706UFj450Xlv9l1oH5D32OEKT2EwfxMqdrw39+N8zD5ehVyQbYM6Z3lwtCvg=
      on:
        tags: true

language: python

matrix:
  include:
    - os: linux
      python: '3.8'
      stage: Lint
      <<: *lint_job

    - os: linux
      python: '3.5'
      env:
        - CONDA=false
        - PYTEST_ARGS=--benchmark-skip
      stage: Test
      <<: *test_job

    - os: linux
      python: '3.8'
      env:
        - CONDA=false
        - PYTEST_ARGS=--benchmark-skip
      stage: Test
      <<: *test_job

    - os: linux
      python: '3.8'
      env:
        - CONDA=false
        - PYTEST_ARGS=--benchmark-only
      stage: Test
      <<: *test_job

    - os: linux
      python: '3.5'
      env:
        - CONDA=true
        - PYTEST_ARGS=--benchmark-skip
      stage: Test
      <<: *test_job

    - os: linux
      python: '3.8'
      env:
        - CONDA=true
        - PYTEST_ARGS=--benchmark-skip
      stage: Test
      <<: *test_job

    - os: linux
      python: '3.8'
      stage: Deploy
      <<: *deploy_job
