channels:
    - conda-forge
dependencies:
    - python=3.7
    - ipython
    - numpy
    - numba
    - scipy
    - sparse
    - matplotlib
    - pandoc
    - ipykernel
    - nbsphinx
    - nbconvert=5.4.1
